name: Deploy Packer Template on Merge

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.8.6/packer_1.8.6_linux_amd64.zip
          unzip packer_1.8.6_linux_amd64.zip
          sudo mv packer /usr/local/bin/
          packer --version
        shell: bash

      - name: Initialize Packer Plugins
        run: packer init ./packer_templates/.

      # - name: Edit .env file
      #   run: |
      #     touch .env
      #     echo DB_NAME=${{ secrets.DB_NAME }} >> .env
      #     echo DB_USER=${{ secrets.WEBAPP_DB_USER}} >> .env
      #     echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
      #     echo DB_HOST=${{ secrets.DB_HOST }} >> .env
      #     echo DB_DIALECT=${{ secrets.DB_DIALECT }} >> .env

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Zip Project Files
        run: zip -r webapp.zip . --exclude=*.git*

      - name: Deploy Packer Template
        run: packer build ./packer_templates/.

      - name: Create New Launch Template Version
        run: |
          LATEST_AMI_ID=$(aws ec2 describe-images --owners self --query 'Images | sort_by(@, &CreationDate) | [-1].ImageId' --output text)
          aws ec2 create-launch-template-version --launch-template-id asg_launch_config_v2 --source-version $LATEST_VERSION --launch-template-data "{\"ImageId\":\"$LATEST_AMI_ID\"}"

      - name: Issue Instance Refresh Command
        id: refresh_instances
        run: |
          INSTANCE_REFRESH_ID=$(aws autoscaling start-instance-refresh --auto-scaling-group-name webAppAutoScalingGroup --query 'InstanceRefreshId' --output text)
          echo "Instance Refresh ID: $INSTANCE_REFRESH_ID"

      - name: Wait for Instance Refresh to Complete
        run: |
          while true; do
            STATUS=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name webAppAutoScalingGroup --instance-refresh-ids $INSTANCE_REFRESH_ID --query 'InstanceRefreshes[0].Status' --output text)
            if [ "$STATUS" = "Successful" ]; then
              echo "Instance refresh completed successfully"
              exit 0
            elif [ "$STATUS" = "Failed" ]; then
              echo "Instance refresh failed"
              exit 1
            fi
            sleep 30
          done
